# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TCDemo

  pod 'PKHUD'
  pod 'Alamofire', '~> 4.9.1'
  pod 'IGListKit'
  pod 'SDWebImage'
  pod 'lottie-ios', '~> 3.2.1'#上传进度条
  pod 'SnapKit'
  pod 'Giphy', '~> 1.3.0'
  pod 'WCDB.swift'
  pod 'HyphenateChat', '~> 3.9.7.1'
  pod 'EMVoiceConvert'
  pod 'MJRefresh'
  pod 'FMDB'
  pod 'AWSS3'

end
